### ISSUE TITLE
Support for YAML templates

### ISSUE THREAD

**Issue by pplu** [pplu/cfn-perl#23]
CloudFormation accepts templates in JSON and YAML.

YAML templates make use of YAML tags to call functions:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ClientSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref 'AWS::StackName'
      VpcId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}
```

We should be able to generate the same object model from YAML than from JSON (they represent the same thing)

**Comment by pplu** [comment]
The only parser that has the potential for doing something with tags is `YAML::PP`. Although stated that tags are completely ignored (https://metacpan.org/pod/YAML::PP#Tags) there seems to be code for handling tags.

@perlpunk: Can you advise me on how I can wire up `YAML::PP` so I can run some custom routine when a tag is found?

**Comment by perlpunk** [comment]
> Although stated that tags are completely ignored

Oops, that's a leftover ;-)

Currently standard tags are handled, and you can define your own constructors for scalar tags, but it seems your use case is to dump YAML with tags from a data structure with objects.
This is currently in the works and released as a developer release, but the inner API of it might change.

Here's a quick example of how you could use this with v0.10_002:
```
use YAML::PP;
my $data = {
    Properties => {
        GroupDescription => (bless {}, 'AWS::StackName'),
        VpcId => {
          'Fn::ImportValue' => (bless {}, 'ParentVPCStack' ),
        },
    },
};

#    Properties:
#      GroupDescription: !Ref 'AWS::StackName'
#      VpcId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}

my $yp = YAML::PP->new();

$yp->schema->add_representer(
    class_equals => 'AWS::StackName',
    code => sub {
        my ($representer, $node) = @_;
        # $node->{value} contains the object
        $node->{tag} = '!Ref';
        $node->{data} = 'AWS::StackName';
        return 1;
    },
);
$yp->schema->add_representer(
    class_equals => 'ParentVPCStack',
    code => sub {
        my ($representer, $node) = @_;
        $node->{tag} = '!Sub';
        $node->{data} = '${ParentVPCStack}-VPC';
        return 1;
    },
);

my $yaml = $yp->dump_string($data);
```

**Comment by pplu** [comment]
> Currently standard tags are handled, and you can define your own constructors for scalar tags, but it seems your use case is to dump YAML with tags from a data structure with objects.

I'm actually interested in being able to read the YAML with tags and covert that into the object model. I would like to "hook in" to the parse process when there is a tag, and insert some special value to the resulting hashref that gets returned.

> This is currently in the works and released as a developer release, but the inner API of it might change.

I'll adapt if there is breakage :)

> Here's a quick example of how you could use this with v0.10_002:

Thanks for the example! This covers the use case of converting the object model to YAML, which I'll play around with a bit to give you feedback. It would be great if you can point me in the right direction for the use case of reading a YAML with tags, hooking into the parse process to get the tags out. Is this possible?

**Comment by pplu** [comment]
Hi @perlpunk : Following your pointers, I've come up with this: https://github.com/pplu/cfn-perl/blob/feature/yaml_support/test_yaml. It generates the desired output:

```yaml
---
Resources:
  R1:
    Properties:
      Groups:
      - Group1
      - Group2
      Path: !Ref AWS::StackName
    Type: AWS::IAM::User
  R2:
    Properties:
      Path: !Ref R1
    Type: AWS::IAM::User
  R3:
    Properties:
      Path: !GetAtt R1.Arn
    Type: AWS::IAM::User
```
Thinking about maintenance: I haven't found out how to control some aspects of the serialization process: There doesn't seem to be a way to do a "class_isa" on the representers. In my case, I can handle a lot of classes with one representer. I even have the case where the values will be from non-preknown subclasses, but with one common ancestor. From what I've navigated through YAML::PP, I think this feature would be implemented here https://metacpan.org/source/TINITA/YAML-PP-0.010_002/lib/YAML/PP/Representer.pm#L181. Are you interested in such a feature?
